-- Purpose: Creating database + primary HR Attrition table
CREATE DATABASE hr_project;
USE hr_project;

CREATE TABLE hr_attrition1 (
  Attrition VARCHAR(5),
  BusinessTravel VARCHAR(50),
  AgeBand VARCHAR(50),
  AttritionLabel VARCHAR(20),
  Department VARCHAR(50),
  EducationField VARCHAR(50),
  EmpID VARCHAR(20),
  EmployeeNumber VARCHAR(20),
  Gender VARCHAR(10),
  JobRole VARCHAR(50),
  MaritalStatus VARCHAR(20),
  OverTime VARCHAR(5),
  Over18 VARCHAR(5),
  TrainingTimesLastYear INT,
  Age INT,
  CF_current_Employee VARCHAR(5),
  DailyRate INT,
  DistanceFromHome INT,
  Education VARCHAR(50),
  EmployeeCount INT,
  EnvironmentSatisfaction INT,
  HourlyRate INT,
  JobInvolvement INT,
  JobLevel INT,
  JobSatisfaction INT,
  MonthlyIncome INT,
  MonthlyRate INT,
  NumCompaniesWorked INT,
  PercentSalaryHike INT,
  PerformanceRating INT,
  RelationshipSatisfaction INT,
  StandardHours INT,
  StockOptionLevel INT,
  TotalWorkingYears INT,
  WorkLifeBalance INT,
  YearsAtCompany INT,
  YearsInCurrentRole INT,
  YearsSinceLastPromotion INT,
  YearsWithCurrManager INT
);
